### ISSUE TITLE
Haraka crashin. TypeError Cannot read property 'uuid' of null

### ISSUE THREAD

**Issue by apmcodes** [nodemailer/haraka-plugin-wildduck#2]
Can you please guide what might be causing this?

```
2018-11-11T22:22:05.758Z [CRIT] [-] [core] TypeError: Cannot read property 'uuid' of null
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at hookDone (/etc/haraka/node_modules/haraka-plugin-wildduck/index.js:234:93)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at plugin.db.userHandler.resolveAddress (/etc/haraka/node_modules/haraka-plugin-wildduck/index.js:553:24)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at users.collection.findOne (/etc/haraka/node_modules/wildduck/lib/user-handler.js:164:48)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at result (/etc/haraka/node_modules/mongodb/lib/utils.js:414:17)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at session.endSession (/etc/haraka/node_modules/mongodb/lib/utils.js:401:11)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at ClientSession.endSession (/etc/haraka/node_modules/mongodb-core/lib/sessions.js:129:41)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at executeCallback (/etc/haraka/node_modules/mongodb/lib/utils.js:397:17)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at handleCallback (/etc/haraka/node_modules/mongodb/lib/utils.js:128:55)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at cursor.next (/etc/haraka/node_modules/mongodb/lib/operations/collection_ops.js:570:5)
2018-11-11T22:22:05.758Z [CRIT] [-] [core]     at result (/etc/haraka/node_modules/mongodb/lib/utils.js:414:17)
2018-11-11T22:22:05.759Z [NOTICE] [-] [core] Shutting down

```

**Comment by rqelibari** [comment]
Hi @andris9,

We are seeing the same error in the docker container. This error seems to be serious, as it shuts down the inbound SMTP server nearly every 6 to 7 hours. Do you have any hint on what might be the problem here?

The file has changed since this error was reported so that the current line of interest is [363](https://github.com/nodemailer/haraka-plugin-wildduck/blob/30727a68c155420fb404eb8d25bd0bd9617b1c77/index.js#L363).

**Comment by andris9** [comment]
I haven't seen this myself but I guess it happens if Haraka clears the `connection.transaction` object (timeout maybe? or some transaction error?)

Anyway, it should be fixed now, I changed the code to cache the uuid variable at the beginning of the hook.
